<?php
/**
 * Created by PhpStorm.
 * User: lance
 * Date: 2016/10/13
 * Time: 11:58
 */
namespace App;
use Illuminate\Database\Eloquent\Model;
Class Student extends Model{
//指定表名
    protected $table= "student";
//指定主键
    protected $primaryKey="id";
//维护时间戳
    public $timestamps=true;
//指定允许批量赋值的字段
    protected $fillable=["name","age"];
//    指定不允许批量赋值的字段
    protected $guarded=[];

    public function getDateFormat()
    {
        return time();
    }
    public function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }
}